<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class initSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * php artisan db:seed --class=initSeeder
     * @return void
     */
    public function run()
    {
        DB::table("products")->insert([
            [
                "id" => 1,
                "name" => "Dr.K",
                "price" => 3000,
                "img1" => "cat1.jpg",
                "img2" => "",
                "description" => "Dr.Kです。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 1,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "name" => "港のヨー子",
                "price" => 3000,
                "img1" => "cat2.jpg",
                "img2" => "cat2_p.jpg",
                "description" => "港のヨー子です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 2,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 3,
                "name" => "義仲",
                "price" => 3000,
                "img1" => "cat3.jpg",
                "img2" => "cat3_p.jpg",
                "description" => "義仲です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 3,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 4,
                "name" => "巴",
                "price" => 3000,
                "img1" => "cat4.jpg",
                "img2" => "cat4_p.jpg",
                "description" => "巴です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 4,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "name" => "義高",
                "price" => 3000,
                "img1" => "cat5.jpg",
                "img2" => "cat5_p.jpg",
                "description" => "義高です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 5,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "name" => "小枝",
                "price" => 3000,
                "img1" => "cat6.jpg",
                "img2" => "",
                "description" => "小枝です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 6,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "name" => "山吹",
                "price" => 3000,
                "img1" => "cat7.jpg",
                "img2" => "",
                "description" => "山吹です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 7,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 8,
                "name" => "大福",
                "price" => 3000,
                "img1" => "cat8.jpg",
                "img2" => "cat8_p.jpg",
                "description" => "大福です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 8,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 9,
                "name" => "シェバ",
                "price" => 3000,
                "img1" => "cat9.jpg",
                "img2" => "",
                "description" => "シェバです。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 9,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 10,
                "name" => "寿々",
                "price" => 3000,
                "img1" => "cat10.jpg",
                "img2" => "",
                "description" => "寿々です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 10,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 11,
                "name" => "白龍　青龍",
                "price" => 4000,
                "img1" => "cat11.jpg",
                "img2" => "cat11_p.jpg",
                "description" => "白龍　青龍です。",
                "releaseYear" => 2023,
                "releaseMonth" => 8,
                "releaseDate" => 1,
                "order" => 11,
                "situation" => "販売中",
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
}
